[project]
name = "markitdowndemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "markitdown>=0.0.1a2",
    "openai>=1.57.4",
    "requests>=2.32.3",
]
